model: "vit_small_patch16_224"
data_set: "Kinetics-400"
nb_classes: 3
data_path: "/root/volume/data/mouse/"
data_root: "/root/volume/data/mouse/"
det_anno_path: "/root/volume/data/mouse/detections"
finetune: "/root/volume/mvd_s_from_b_ckpt_399.pth"
output_dir: "/root/volume/OUTPUT/MP_TRAIN_3_maximal_crop"
input_size: 224
short_side_size: 224
opt: adamw
opt_betas: 0.9 0.999
weight_decay: 0.001
batch_size: 12
update_freq: 1
num_sample: 2
save_ckpt_freq: 2
num_frames: 16
sampling_rate: 2
reprob: 0.05
mixup_prob: 0.05
lr: 5e-4
epochs: 40
warmup_epochs: 2
dist_eval: true
num_workers: 12
test_num_segment: 1
test_num_crop: 1
enable_deepspeed: true
