# Training Duration
epochs: 1 # 20 # (int) Total number of training epochs.
save_ckpt_freq: 1 # 5 # (int) Save checkpoint every N epochs.

# Dataset
val_ratio: 0.2 # (float) Validation ratio.

#  Optimization
lr: 5e-4 # (float | str) Base learning rate; scaled proportionally to batch size inside the script.
batch_size: 1 # 12  # (int) Batch size (videos) per GPU before gradient accumulation.
warmup_epochs: 0 # 2  # (int) Number of epochs for learning rate warmup.
opt: adamw  # (str) Optimizer type (adamw, sgd, etc.).
opt_betas: 0.9 0.999  # (str) β1 and β2 coefficients for AdamW.
weight_decay: 0.001  # (float) L2 weight regularization.

# Model Input
input_size: 224 # (int) Spatial resolution of input clip.
num_frames: 2 # 16 # (int) Number of frames in one video clip.
sampling_rate: 2 # (int) Time step between selected frames.
short_side_size: 224 # (int) Short side of the frame during augmentation/evaluation.

# Augmentation
num_sample: 2 # (int) Repeated Augmentation factor.
reprob: 0.05 # (float) Random Erasing probability.
mixup_prob: 0.05 # (float) Mixup/CutMix application probability.

# Training distribution
update_freq: 1 # (int) Gradient accumulation steps.
enable_deepspeed: false # (bool) Enable DeepSpeed engine for efficient distributed training.
dist_eval: true # (bool) Perform evaluation in distributed mode.
num_workers: 2 # 12 # (int) Number of DataLoader workers.

# Validation/Test
test_num_segment: 1 # (int) Number of temporal segments during testing.
test_num_crop: 1 # (int) Number of spatial crops during testing.
