# Training Duration
epochs: 20 # (int) Total number of training epochs.
save_ckpt_freq: 5 # (int) Save checkpoint every N epochs.

# Dataset
val_ratio: 0.15 # (float) Validation ratio.

#  Optimization
lr: 5e-4 # (float | str) Base learning rate; scaled proportionally to batch size inside the script.
batch_size: 8 # (int) Batch size (videos) per GPU before gradient accumulation.
warmup_epochs: 0 # (int) Number of epochs for learning rate warmup.
opt: adamw  # (str) Optimizer type (adamw, sgd, etc.).
opt_betas: 0.9 0.999  # (str) β1 and β2 coefficients for AdamW.
weight_decay: 0.001  # (float) L2 weight regularization.

# Model Input
input_size: 224 # (int) Spatial resolution of input clip.
num_frames: 16 # (int) Number of frames in one video clip.
sampling_rate: 2 # (int) Time step between selected frames.

# Augmentation
reprob: 0.05 # (float) Random Erasing probability.
mixup_prob: 0.05 # (float) Mixup/CutMix application probability.

# Training distribution
update_freq: 1 # (int) Gradient accumulation steps.
enable_deepspeed: true # (bool) Enable DeepSpeed engine for efficient distributed training.
num_workers: 6 # (int) Number of DataLoader workers.
