ARG RT_DETR_IMAGE
FROM ${RT_DETR_IMAGE}

WORKDIR /app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/* && \
    git clone https://github.com/supervisely-ecosystem/RT-DETRv2.git . && \
    rm -rf .git

ARG MODEL_PATH

COPY ${MODEL_PATH} /models/rtdetr/

ENTRYPOINT ["python3", "supervisely_integration/serve/main.py", "deploy", "--model", "/models/rtdetr/checkpoints/best.pth"]
