services:
  rt-detr:
    image: supervisely/mvd:rtdetrv2-1.0.0
    runtime: nvidia
    environment:
      PYTHONPATH: /app
      # TEAM_ID: 17
      # API_TOKEN: ""
      # SERVER_ADDRESS: https://dev.supervisely.com
    env_file:
      - .env
    volumes:
      - ./models:/models
    command:
      - deploy
      - --model
      - /models/1089_RT-DETRv2/checkpoints/best.pth

  mvd:
    image: supervisely/mvd:inference-1.0.0
    runtime: nvidia
    environment:
      PYTHONPATH: /app
      MODEL_DIR: /models/mvd
      # TEAM_ID: 17
      # API_TOKEN: ""
      # SERVER_ADDRESS: https://dev.supervisely.com
    env_file:
      - .env
    volumes:
      - ..:/app
      - ${MODEL_DIR}:/models/mvd
      - ${INPUT}:/input
      - ${OUTPUT}:/output
    working_dir: /app
    command: python3 /app/inference_script/run_inference.py
    depends_on:
      - rt-detr
