services:
  rt-detr:
    build:
      context: .
      dockerfile: Dockerfile.rt-detr-app
      args:
        RT_DETR_IMAGE: supervisely/rt-detrv2:1.0.11
    # container_name: supervisely-utils-rtdetrv2-inference-1
    runtime: nvidia
    environment:
      PYTHONPATH: /app
    env_file:
      - .env
    volumes:
      - ${RT_DETR_MODEL}:/models/rtdetr
    working_dir: /app
    ports:
      - ${RT_DETR_PORT}:8000
    command: python3 supervisely_integration/serve/main.py deploy --model /models/rtdetr/checkpoints/best.pth

  mvd:
    image: supervisely/mvd:inference-0.0.1
    runtime: nvidia
    environment:
      PYTHONPATH: /app
    env_file:
      - .env
    volumes:
      - ..:/app
      - ${MVD_MODEL}:/models/mvd
      - ${INPUT}:/input
      - ${OUTPUT}:/output
    working_dir: /app
    command: python3 /app/inference_script/run_inference.py
    depends_on:
      - rt-detr
      
  benchmark:
    image: supervisely/mvd:inference-0.0.1
    runtime: nvidia
    profiles:
      - benchmark
    environment:
      PYTHONPATH: /app
    env_file:
      - .env
    volumes:
      - ..:/app
      - ${INPUT}:/input
      - ${OUTPUT}:/output
    working_dir: /app
    command: python3 /app/inference_script/run_benchmark.py
